name: publish release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '20'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.6

      - name: Create new buildx builder
        run: docker buildx create --name custom_builder --use

      - name: Build application
        run: ./gradlew build -Dquarkus.package.jar.type=uber-jar

      - name: Build images
        run: docker buildx build --platform=linux/amd64 --platform=linux/arm64 -t bolzerdev/peppol-bis-billing-validator:${{github.ref_name}} -t bolzerdev/peppol-bis-billing-validator:latest  . --push
